packages:
  - "apps/*"
  - "lib/*"

allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true
  lefthook: true
  msw: true
  sharp: true

minimumReleaseAgeExclude:
  - '@scalar/client-side-rendering@0.3.6'
  - '@scalar/fastify-api-reference@1.64.1'
  - '@scalar/helpers@0.10.0'
  - '@scalar/json-magic@0.12.20'
  - '@scalar/openapi-parser@0.28.12'
  - '@scalar/openapi-upgrader@0.2.13'
  - '@scalar/schemas@0.8.1'
  - '@scalar/types@0.17.1'
  - discord-api-types@0.38.53
  - lucide-react@1.30.0
  - tsx@4.23.11
