packages:
  - "apps/*"
  - "lib/*"

allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true
  lefthook: true
  msw: true
  sharp: true

minimumReleaseAgeExclude:
  - typebox@1.2.19
