packages:
  - "apps/*"
  - "lib/*"

allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true
  lefthook: true
  msw: true
  sharp: true

minimumReleaseAgeExclude:
  - '@types/react-dom@19.2.4'
  - '@types/react@19.2.18'
  - fastify@5.11.0
  - lucide-react@1.28.0
